URL = 'http://mattmahoney.net/dc/text8.zip'
EXPECTED_BYTES = 31344016
LOCAL_DATA_DIR = 'data/'

TRAIN_STEPS = 1000000
PRINT_FREQ = TRAIN_STEPS // 10
EVAL_FREQ = TRAIN_STEPS // 10
TEST_FREQ = TRAIN_STEPS // 10

RESULT_DIR = "result/"
